### ISSUE TITLE
请问一下(?i:class)这个忽略大小写的语法是在哪里看到的啊？

### ISSUE THREAD

**Issue by widon1104** [luyi0619/cool-compiler#1]
/*
  * Keywords are case-insensitive except for the values true and false,
  * which must begin with a lower-case letter.
  */
(?i:class)		                        { return CLASS; }
(?i:else)	{ return ELSE; }

**Comment by luyi0619** [comment]
some lex tutorial. I do not really remember it since it was years ago.
